# Name of workflow
name: Build
# Trigger on all pull-request
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build and test the app
        run: ./gradlew clean test assembleDebug --stacktrace